enum MATERIAL
{
	AIR,
	STONE,
	FUNGUS,
	TITANIUM,
	COUNT
}

//IS_SOLID
global.MATERIAL_IS_SOLID = array_create(MATERIAL.COUNT,true);
global.MATERIAL_IS_SOLID[MATERIAL.AIR] = false;

//SPRITE
global.MATERIAL_SPRITE = array_create(MATERIAL.COUNT,-1);
global.MATERIAL_SPRITE[MATERIAL.STONE] = SprStone;
global.MATERIAL_SPRITE[MATERIAL.FUNGUS] = SprFungus;
global.MATERIAL_SPRITE[MATERIAL.TITANIUM] = SprTitanium;

//HEALTH
global.MATERIAL_HEALTH = array_create(MATERIAL.COUNT,1);
global.MATERIAL_HEALTH[MATERIAL.STONE] = 3;
global.MATERIAL_HEALTH[MATERIAL.TITANIUM] = -1;